"""Department CRUD routes (generated by the master-data engine)."""

from fastapi import APIRouter

from app.api.master_data_routes import build_router
from app.core.master_data import DEPARTMENT_SPEC

router: APIRouter = build_router(DEPARTMENT_SPEC)
