"""add audit_intents outbox table

Revision ID: c0ec9628f6f4
Revises: d945881eedfd
Create Date: 2026-09-03 09:02:16.315555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c0ec9628f6f4'
down_revision: Union[str, Sequence[str], None] = 'd945881eedfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_intents_created_at'), 'audit_intents', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_intents_created_at'), table_name='audit_intents')
    op.drop_table('audit_intents')
    # ### end Alembic commands ###
