"""add audit hash chain to audit_logs

Revision ID: d945881eedfd
Revises: f17febf561e3
Create Date: 2026-09-03 08:46:36.172187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd945881eedfd'
down_revision: Union[str, Sequence[str], None] = 'f17febf561e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('seq', sa.BigInteger(), nullable=True))
    op.add_column('audit_logs', sa.Column('prev_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('entry_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_index(op.f('ix_audit_logs_seq'), 'audit_logs', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_seq'), table_name='audit_logs')
    op.drop_column('audit_logs', 'entry_hash')
    op.drop_column('audit_logs', 'prev_hash')
    op.drop_column('audit_logs', 'seq')
    # ### end Alembic commands ###
