"""add exports table

Revision ID: f17febf561e3
Revises: d08a5d22d172
Create Date: 2026-08-31 13:02:45.855130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f17febf561e3'
down_revision: Union[str, Sequence[str], None] = 'd08a5d22d172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_format', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('generation_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_created_at'), 'exports', ['created_at'], unique=False)
    op.create_index(op.f('ix_exports_created_by'), 'exports', ['created_by'], unique=False)
    op.create_index(op.f('ix_exports_expires_at'), 'exports', ['expires_at'], unique=False)
    op.create_index(op.f('ix_exports_module'), 'exports', ['module'], unique=False)
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_index(op.f('ix_exports_module'), table_name='exports')
    op.drop_index(op.f('ix_exports_expires_at'), table_name='exports')
    op.drop_index(op.f('ix_exports_created_by'), table_name='exports')
    op.drop_index(op.f('ix_exports_created_at'), table_name='exports')
    op.drop_table('exports')
    # ### end Alembic commands ###
