"""master data students schema

Revision ID: f3e16adb471b
Revises: f17febf561e3
Create Date: 2026-09-01 22:43:25.029675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3e16adb471b'
down_revision: Union[str, Sequence[str], None] = 'f17febf561e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_country_code'), 'countries', ['country_code'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('building', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('state_province', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advisor_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('office_room', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('degree_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('advisor_id', sa.Uuid(), nullable=True),
    sa.Column('program_id', sa.Uuid(), nullable=True),
    sa.Column('mentor_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('semester', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', 'semester', name='uq_enrollment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_table('programs')
    op.drop_table('courses')
    op.drop_table('advisors')
    op.drop_table('addresses')
    op.drop_table('departments')
    op.drop_index(op.f('ix_countries_country_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
